/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
calc_mean_1(y_vector *argp, CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calc_mean,
		(xdrproc_t) xdr_y_vector, (caddr_t) argp,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

min_max *
find_min_max_1(y_vector *argp, CLIENT *clnt)
{
	static min_max clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FIND_MIN_MAX,
		(xdrproc_t) xdr_y_vector, (caddr_t) argp,
		(xdrproc_t) xdr_min_max, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

scale_result *
scale_multiply_1(scale_input *argp, CLIENT *clnt)
{
	static scale_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCALE_MULTIPLY,
		(xdrproc_t) xdr_scale_input, (caddr_t) argp,
		(xdrproc_t) xdr_scale_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
