/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
calc_mean_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		y_vector calc_mean_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case calc_mean:
		_xdr_argument = (xdrproc_t) xdr_y_vector;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) calc_mean_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calc_min_max_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		y_vector find_min_max_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FIND_MIN_MAX:
		_xdr_argument = (xdrproc_t) xdr_y_vector;
		_xdr_result = (xdrproc_t) xdr_min_max;
		local = (char *(*)(char *, struct svc_req *)) find_min_max_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calc_scale_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		scale_input scale_multiply_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SCALE_MULTIPLY:
		_xdr_argument = (xdrproc_t) xdr_scale_input;
		_xdr_result = (xdrproc_t) xdr_scale_result;
		local = (char *(*)(char *, struct svc_req *)) scale_multiply_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (calc_mean_PROG, calc_mean_VERS);
	pmap_unset (calc_min_max_PROG, calc_min_max_VERS);
	pmap_unset (calc_scale_PROG, calc_scale_result_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, calc_mean_PROG, calc_mean_VERS, calc_mean_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (calc_mean_PROG, calc_mean_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, calc_min_max_PROG, calc_min_max_VERS, calc_min_max_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (calc_min_max_PROG, calc_min_max_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, calc_scale_PROG, calc_scale_result_VERS, calc_scale_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (calc_scale_PROG, calc_scale_result_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, calc_mean_PROG, calc_mean_VERS, calc_mean_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (calc_mean_PROG, calc_mean_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, calc_min_max_PROG, calc_min_max_VERS, calc_min_max_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (calc_min_max_PROG, calc_min_max_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, calc_scale_PROG, calc_scale_result_VERS, calc_scale_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (calc_scale_PROG, calc_scale_result_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
